steps:
- name: node:12.16.3
  entrypoint: yarn
  args: ['install', '--pure-lockfile', '--cache-folder', '.yarn-cache']
- name: node:12.16.3
  entrypoint: yarn
  args: ['build']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: 300s
